apiVersion: apps/v1
kind: Deployment
metadata:
  name: uop-voting
  labels:
    uop-label: uop-voting
spec:
  selector:
    matchLabels:
      uop-label: uop-voting
  template:
    metadata:
      labels:
        uop-label: uop-voting
    spec:
      containers:
        - name: voting-machine
          image: ikonomou/uop-test:v3
          imagePullPolicy: Always
          ports:
            - name: http-voting
              containerPort: 8090
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: uop-voting-service
spec:
  ports:
    - protocol: TCP
      name: web
      port: 80
      targetPort: 8090
  selector:
    uop-label: uop-voting
  type: LoadBalancer
